# Generated by Django 3.1.2 on 2020-12-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='producto',
        ),
    ]
