# Generated by Django 3.1.2 on 2020-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20201222_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
